# version: '3.8'
services:
  ros-simulation:
    image: formula-simulation
    # runtime: nvidia
    container_name: formula_simulation
    volumes:
      - ./:/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - SDL_VIDEODRIVER=x11
    command: bash
    privileged: true
    network_mode: host
    stdin_open: true
    tty: true